version: 2
updates:
  - package-ecosystem: npm
    directory: '/Docs'
    versioning-strategy: increase
    commit-message:
      prefix: 'build(npm)'
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: '/'
    commit-message:
      prefix: 'ci'
    schedule:
      interval: weekly
