version: 2
updates:
  - package-ecosystem: npm
    directory: '/Docs'
    versioning-strategy: increase
    commit-message:
      prefix: 'docs(npm)'
    schedule:
      interval: weekly
    groups:
      dev:
        dependency-type: development
        applies-to: version-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: '/'
    commit-message:
      prefix: 'ci'
    schedule:
      interval: weekly
