version: 2
updates:
  - package-ecosystem: npm
    directory: '/Docs'
    versioning-strategy: increase
    commit-message:
      prefix: 'docs(npm)'
    schedule:
      interval: weekly
    groups:
      npm-dev-minor:
        dependency-type: development
        applies-to: version-updates
        patterns: ['*']
        update-types:
          - minor
          - patch
      npm-dev-major:
        dependency-type: development
        applies-to: version-updates
        patterns: ['*']
        update-types:
          - major
  - package-ecosystem: github-actions
    directory: '/'
    commit-message:
      prefix: 'ci(actions)'
    schedule:
      interval: weekly
