name: Code Analysis

on:
  push:
    branches:
      - latest
    paths:
      - '.github/workflows/**.yml'
      - 'Accept AirPlay Requests/**.swift'
      - 'Docs/**.ts'
  pull_request:
    branches:
      - latest
    paths:
      - '.github/workflows/**.yml'
      - 'Accept AirPlay Requests/**.swift'
      - 'Docs/**.ts'

permissions:
  contents: read
  actions: read
  checks: write
  security-events: write
  
defaults:
  run:
    shell: bash
  
jobs:
  codeql:
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: Swift
            build-mode: autobuild
            source-root: 'Accept AirPlay Requests'
            runner: macos-15
          - language: TypeScript
            source-root: 'Docs/.vuepress'
          - language: Actions
    name: CodeQL (${{ matrix.language }})
    runs-on: ${{ matrix.runner || 'ubuntu-latest' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}-${{ matrix.language }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: CodeQL Initialize
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode || 'none' }}
          source-root: ${{ matrix.source-root }}
          queries: security-and-quality
          dependency-caching: true
          trap-caching: true
      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: ${{ matrix.language }}
