name: Documentation

on:
  push:
    branches:
      - latest
  pull_request:
    branches:
      - latest

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write
  pages: write

defaults:
  run:
    shell: bash

jobs:
  build:
    name: VuePress Build
    runs-on: macos-latest
    timeout-minutes: 10
    env:
      DOCS_DIR: ${{ github.workspace }}/Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ${{ env.DOCS_DIR }}/package-lock.json
      - name: Install npm dependencies
        working-directory: ${{ env.DOCS_DIR }}
        run: npm clean-install
      - name: Build VuePress static site
        working-directory: ${{ env.DOCS_DIR }}
        run: npm run build
      - if: github.ref_name == 'latest'
        name: Setup GitHub Pages
        uses: actions/configure-pages@v5  
      - if: github.ref_name == 'latest'
        name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DOCS_DIR }}/.vuepress/dist

  deploy:
    if: github.ref_name == 'latest'
    name: Deploy to Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Deploy build to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
