name: Unit Testing

on:
  push:
    branches:
      - latest
    paths:
      - '.github/workflows/test.yml'
      - 'Accept AirPlay Requests/**'
  pull_request:
    branches:
      - latest
    paths:
      - '.github/workflows/test.yml'
      - 'Accept AirPlay Requests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  actions: read
  
defaults:
  run:
    shell: bash
  
jobs:
  swift:
    name: Swift Testing
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      SWIFT_VERSION: '6'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Swift ${{ env.SWIFT_VERSION }}
        uses: swift-actions/setup-swift@682457186b71c25a884c45c06f859febbe259240
        with:
          swift-version: ${{ env.SWIFT_VERSION }}
      - name: Test Swift Package
        working-directory: 'Accept AirPlay Requests'
        run: swift test -v
